### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by Bhushan0246** [Bhushan0246/Hacktoberfest#1]

**Comment by sid-1207** [comment]
Is there any issue open
I would like to contribue

**Comment by Bhushan0246** [comment]
Sure you can contribute in _js, java, python_ and more ...
The projects made with such lang.
In addition you can contribute with languages whose folders are not even made (e.x- Kotlin, go, etc...) by making a folder by lang name and adding your project to it @sid-1207

**Comment by Bhushan0246** [comment]
And do star and fork the repo.

**Comment by sid-1207** [comment]
@Bhushan0246 sure thanks I ll do it

**Comment by Haid-Faiz** [comment]
@Bhushan0246 Hi, i want to contribute in Kotlin... I will add kotlin folder then kotlin file of quick sort sort algorithm.
