### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by Bhushan0246** [Bhushan0246/Hacktoberfest#20]
You can add _**Games**_ too in repo made in any language.

**Comment by Error404m** [comment]
Interested, pl assign.

**Comment by kaustavy2k** [comment]
Please assign it to me. i will add a game written in js

**Comment by hidalgo-vntu** [comment]
can I add game on python ?

**Comment by Bhushan0246** [comment]
Sure @hidalgo-vntu you can add it under Python folder 🚀

**Comment by Bhushan0246** [comment]
> Please assign it to me. i will add a game written in js

Go ahead @kaustavy2k
